pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo "Repository cloned automatically"
            }
        }

        stage('Build') {
            steps {
                sh 'this thing does not even exist'
                sh 'sleep 5'
            }
        }

        stage('Test') {
            steps {
                sh 'echo Running tests !!!'
                sh 'sleep 3'
            }
        }

        stage('Package') {
            steps {
                sh 'echo Packaging artifact !!!'
            }
        }

    }

    post {

        always {
            echo "Pipeline Finished"
        }

        success {
            echo "SUCCESS"
        }

        failure {
            echo "FAILED"
        }

    }

}
